# This file is distributed under the same license as the Django package.
#
# Translators:
# Jannis Leidel <jannis@leidel.info>, 2011
# arupakan125 <koh@arupaka.net>, 2020
# Masashi SHIBATA <contact@c-bata.link>, 2017
# Nikita K <hiyori.amatsuki@gmail.com>, 2019
# Shinya Okano <tokibito@gmail.com>, 2013-2016,2021,2023-2024
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-04-09 10:01+0700\n"
"PO-Revision-Date: 2024-08-07 08:09+0000\n"
"Last-Translator: Shinya Okano <tokibito@gmail.com>, "
"2013-2016,2021,2023-2024\n"
"Language-Team: Japanese (http://app.transifex.com/django/django/language/"
"ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:49
msgid "Personal info"
msgstr "個人情報"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:51
msgid "Permissions"
msgstr "パーミッション"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:62
msgid "Important dates"
msgstr "重要な日程"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:158
#, python-format
msgid "%(name)s object with primary key %(key)r does not exist."
msgstr "主キーが %(key)r である %(name)s オブジェクトは存在しません。"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:177
msgid "Conflicting form data submitted. Please try again."
msgstr "送信されたフォームデータは競合しています。もう一度試してみてください。"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:185
msgid "Password changed successfully."
msgstr "パスワードを変更しました"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:187
msgid "Password-based authentication was disabled."
msgstr "パスワードによる認証は無効化されました。"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:208
#, python-format
msgid "Change password: %s"
msgstr "パスワードの変更: %s"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:210
#, python-format
msgid "Set password: %s"
msgstr "パスワード設定: %s"

#: .\venv\Lib\site-packages\django\contrib\auth\apps.py:16
msgid "Authentication and Authorization"
msgstr "認証と認可"

#: .\venv\Lib\site-packages\django\contrib\auth\base_user.py:41
msgid "password"
msgstr "パスワード"

#: .\venv\Lib\site-packages\django\contrib\auth\base_user.py:42
msgid "last login"
msgstr "最終ログイン"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:51
msgid "Invalid password format or unknown hashing algorithm."
msgstr "無効なパスワードか不明なハッシュアルゴリズムです。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:59
msgid "No password set."
msgstr "パスワードは設定されませんでした。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:62
msgid "Reset password"
msgstr "パスワードをリセット"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:62
msgid "Set password"
msgstr "パスワードを設定"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:105
msgid "The two password fields didn’t match."
msgstr "確認用パスワードが一致しません。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:109
#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:292
#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:328
msgid "Password"
msgstr "パスワード"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:109
msgid "Password confirmation"
msgstr "パスワード(確認用)"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:122
msgid "Enter the same password as before, for verification."
msgstr "確認のため、再度パスワードを入力してください。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:164
msgid ""
"Whether the user will be able to authenticate using a password or not. If "
"disabled, they may still be able to authenticate using other backends, such "
"as Single Sign-On or LDAP."
msgstr ""
"ユーザーがパスワードを使用して認証できるかどうか。無効にしても、シングルサイ"
"ンオンや LDAP などの他のバックエンドを使用して認証できる可能性があります。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:172
msgid "Password-based authentication"
msgstr "パスワードによる認証"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:175
msgid "Enabled"
msgstr "有効"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:175
msgid "Disabled"
msgstr "無効"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:294
msgid ""
"Raw passwords are not stored, so there is no way to see the user’s password."
msgstr ""
"パスワードは平文では保存されず、ユーザーのパスワードを見る方法もありません。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:310
msgid ""
"Enable password-based authentication for this user by setting a password."
msgstr "パスワードを設定し、このユーザーでパスワードによる認証を有効にします。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:335
#, python-format
msgid ""
"Please enter a correct %(username)s and password. Note that both fields may "
"be case-sensitive."
msgstr ""
"正しい%(username)sとパスワードを入力してください。どちらのフィールドも大文字"
"と小文字は区別されます。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:338
msgid "This account is inactive."
msgstr "アカウントが無効です。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:403
msgid "Email"
msgstr "メールアドレス"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:511
msgid "New password"
msgstr "新しいパスワード"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:511
msgid "New password confirmation"
msgstr "新しいパスワード(確認用)"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:536
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr "元のパスワードが間違っています。もう一度入力してください。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:540
msgid "Old password"
msgstr "元のパスワード"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:349
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:442
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:532
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:627
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:678
msgid "algorithm"
msgstr "アルゴリズム"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:350
msgid "iterations"
msgstr "イテレーション"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:351
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:448
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:534
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:631
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:679
msgid "salt"
msgstr "ソルト"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:352
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:449
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:632
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:680
msgid "hash"
msgstr "ハッシュ"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:443
msgid "variety"
msgstr "多様性"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:444
msgid "version"
msgstr "バージョン"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:445
msgid "memory cost"
msgstr "メモリーコスト"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:446
msgid "time cost"
msgstr "時間コスト"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:447
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:630
msgid "parallelism"
msgstr "並行性"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:533
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:628
msgid "work factor"
msgstr "ワークファクター"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:535
msgid "checksum"
msgstr "チェックサム"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:629
msgid "block size"
msgstr "ブロックサイズ"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:63
#: .\venv\Lib\site-packages\django\contrib\auth\models.py:117
msgid "name"
msgstr "名前"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:67
msgid "content type"
msgstr "コンテンツタイプ"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:69
msgid "codename"
msgstr "コード名"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:74
msgid "permission"
msgstr "パーミッション"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:75
#: .\venv\Lib\site-packages\django\contrib\auth\models.py:120
msgid "permissions"
msgstr "パーミッション"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:127
msgid "group"
msgstr "グループ"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:128
#: .\venv\Lib\site-packages\django\contrib\auth\models.py:259
msgid "groups"
msgstr "グループ"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:250
msgid "superuser status"
msgstr "スーパーユーザー権限"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:253
msgid ""
"Designates that this user has all permissions without explicitly assigning "
"them."
msgstr "全ての権限を持っているとみなされます。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:262
msgid ""
"The groups this user belongs to. A user will get all permissions granted to "
"each of their groups."
msgstr ""
"このユーザーが所属するグループ。ユーザーはそれぞれのグループに付与されたすべ"
"ての権限を持ちます。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:270
msgid "user permissions"
msgstr "ユーザーパーミッション"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:272
msgid "Specific permissions for this user."
msgstr "このユーザーの持つ権限です。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:346
msgid "username"
msgstr "ユーザー名"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:350
msgid "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
msgstr ""
"この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にし"
"てください。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:354
msgid "A user with that username already exists."
msgstr "同じユーザー名が既に登録済みです。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:357
msgid "first name"
msgstr "名"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:358
msgid "last name"
msgstr "姓"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:359
msgid "email address"
msgstr "メールアドレス"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:361
msgid "staff status"
msgstr "スタッフ権限"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:363
msgid "Designates whether the user can log into this admin site."
msgstr "ユーザーが管理サイトにログイン可能かどうかを示します。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:366
msgid "active"
msgstr "有効"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:369
msgid ""
"Designates whether this user should be treated as active. Unselect this "
"instead of deleting accounts."
msgstr ""
"ユーザーがアクティブかどうかを示します。アカウントを削除する代わりに選択を解"
"除してください。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:373
msgid "date joined"
msgstr "登録日"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:382
msgid "user"
msgstr "ユーザー"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:383
msgid "users"
msgstr "ユーザー"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:111
#, python-format
msgid ""
"This password is too short. It must contain at least %(min_length)d "
"character."
msgid_plural ""
"This password is too short. It must contain at least %(min_length)d "
"characters."
msgstr[0] "このパスワードは短すぎます。最低 %(min_length)d 文字以上必要です。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:123
#, python-format
msgid "Your password must contain at least %(min_length)d character."
msgid_plural "Your password must contain at least %(min_length)d characters."
msgstr[0] "パスワードは最低 %(min_length)d 文字以上必要です。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:206
#, python-format
msgid "The password is too similar to the %(verbose_name)s."
msgstr "このパスワードは %(verbose_name)s と似すぎています。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:213
msgid "Your password can’t be too similar to your other personal information."
msgstr "あなたの他の個人情報と似ているパスワードにはできません。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:245
msgid "This password is too common."
msgstr "このパスワードは一般的すぎます。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:250
msgid "Your password can’t be a commonly used password."
msgstr "よく使われるパスワードにはできません。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:261
msgid "This password is entirely numeric."
msgstr "このパスワードは数字しか使われていません。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:266
msgid "Your password can’t be entirely numeric."
msgstr "数字だけのパスワードにはできません。"

#: .\venv\Lib\site-packages\django\contrib\auth\templates\registration\password_reset_subject.txt:2
#, python-format
msgid "Password reset on %(site_name)s"
msgstr "%(site_name)s のパスワードリセット"

#: .\venv\Lib\site-packages\django\contrib\auth\validators.py:12
msgid ""
"Enter a valid username. This value may contain only unaccented lowercase a-z "
"and uppercase A-Z letters, numbers, and @/./+/-/_ characters."
msgstr ""
"有効なユーザー名を入力してください。アクセント記号を除いた半角英数、 @/./+/-/"
"_ を使用できます。"

#: .\venv\Lib\site-packages\django\contrib\auth\validators.py:22
msgid ""
"Enter a valid username. This value may contain only letters, numbers, and "
"@/./+/-/_ characters."
msgstr ""
"有効なユーザー名を入力してください。半角英数、 @/./+/-/_ を使用できます。"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:164
msgid "Logged out"
msgstr "ログアウト"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:224
msgid "Password reset"
msgstr "パスワードをリセット"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:252
msgid "Password reset sent"
msgstr "パスワードリセットを送信しました"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:263
msgid "Enter new password"
msgstr "新しいパスワードを入力してください"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:335
msgid "Password reset unsuccessful"
msgstr "パスワードのリセットに失敗しました"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:345
msgid "Password reset complete"
msgstr "パスワードがリセットされました"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:357
msgid "Password change"
msgstr "パスワードの変更"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:380
msgid "Password change successful"
msgstr "パスワードを変更しました"
